# Generated by Django 5.0.1 on 2024-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sham', '0003_delete_customprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companian',
            field=models.ManyToManyField(blank=True, related_name='companianed_by', to='sham.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='self'),
        ),
    ]
