# Generated by Django 5.0.1 on 2024-01-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sham', '0007_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekh',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_lekh', to='sham.lekh'),
        ),
    ]
