# Generated by Django 5.0.1 on 2024-01-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sham', '0002_customprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomProfile',
        ),
    ]
