# Generated by Django 5.0.1 on 2024-01-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sham', '0006_rename_user_lekh_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_img'),
        ),
    ]
