# Generated by Django 5.0.1 on 2024-01-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sham', '0008_lekh_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekh',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lekh/', verbose_name=''),
        ),
    ]
